trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
 location: 'westeurope'
 resourcegroup: 'ARORG'
 clustername: 'arocluster'

steps:
- task: AzureCLI@2
  displayName: Create ARO
  inputs:
    azureSubscription: 'jovadkerAKS'
    addSpnToEnvironment: true
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
       echo "change chmod to be executable"
       sudo chmod +x $(Build.SourcesDirectory)/iac/deployaro.sh
       $(Build.SourcesDirectory)/iac/deployaro.sh $(location) $(resourcegroup) $(clustername)
      